project:
  name: quickstart-vmware-tanzu-application-platform
  owner: quickstart-eng@amazon.com
  s3_regional_buckets: true
  template: templates/aws-tap-entrypoint-new-vpc.template.yaml
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  build_submodules: true
  parameters:
    AcceptEULAs: --override--
    AcceptCEIP: --override--
    AvailabilityZones: $[taskcat_genaz_3]
    NumberOfAZs: 3
    KeyPairName: --override--
    RemoteAccessCidr: --override--
    EKSClusterName: $[taskcat_random-string]
    TanzuNetUsername: --override--
    TanzuNetPassword: --override--
    TanzuNetApiToken: --override--
    TAPDomainName: --override--
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  regions:
    #! Don't change that without adapting the internal pipeline, we use the
    #! first .project.region as the default for CI buckets (for caching, ...)
    - us-east-1
tests:
  single-cluster:
    parameters:
      TAPClusterArch: single
      TanzuNetRelocateImages: "No"
    regions:
      - us-east-1
      - eu-south-1
  multi-cluster:
    parameters:
      TAPClusterArch: multi
      TanzuNetRelocateImages: "No"
    regions:
      - us-west-2
  relocation-single:
    parameters:
      TAPClusterArch: single
      TanzuNetRelocateImages: "Yes"
    regions:
      - us-west-2
  relocation-multi:
    parameters:
      TAPClusterArch: multi
      TanzuNetRelocateImages: "Yes"
    regions:
      - us-east-1
