#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: metadata-store-secrets
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: store-ca-cert
  namespace: metadata-store-secrets
spec:
  toNamespaces: #@ ["{}".format(data.values.workload.namespace)]
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: store-auth-token
  namespace: metadata-store-secrets
spec:
  toNamespaces: #@  ["{}".format(data.values.workload.namespace)]