#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#! To add more overlays to packages
#!   1. add one or more new secrets here
#!   2. add those secrets to the package_overlay_apply.yml

#@ tapNamespace = data.values.tapNamespace if hasattr(data.values, "tapNamespace") else "tap-install"
#@ tapVersion = data.values.tapVersion
#@ quickstartBuild = data.values.quickstartBuild if hasattr(data.values, "quickstartBuild") else "0"

#@ def tapTelemetryQuickstartConfig(version, build="0"):
kind: ConfigMap
apiVersion: v1
metadata:
  name: quickstart
  namespace: tap-telemetry
data:
  version: #@ '{}+aws.{}'.format(version, build)
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: tap-telemetry-overlays
  namespace: #@ data.values.tapNamespace
stringData:
  quickstart-config.yml: #@ yaml.encode(tapTelemetryQuickstartConfig(tapVersion, quickstartBuild))
---
