---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: tappc-docker-local.artifactory.eng.vmware.com/ci/docker-image
    tag: latest
inputs:
- name: repo
- name: ci-repo
outputs:
- name: repo
run:
  path: ci-repo/ci/tasks/git-force-submodules/task.sh
