// Edit this placeholder text as necessary to describe the deployment options.

This Partner Solution provides the following deployment options:

// Template direct template links
* https://fwd.aws/DJ34n?[Deploy {partner-product-short-name} into a new VPC^]. This option builds a new AWS environment that consists of the VPC, subnets, NAT gateways, security groups, bastion hosts, and other infrastructure components.
  It then deploys {partner-product-short-name} into this new VPC.
* https://fwd.aws/DdRVe?[Deploy {partner-product-short-name} into an existing VPC^]. This option provisions {partner-product-short-name} in your existing AWS infrastructure.

<<<<<<< HEAD
This Partner Solution provides separate templates for these options. It also lets you configure Classless Inter-Domain Routing (CIDR) blocks, instance types, and {partner-product-short-name} settings.
=======
This Quick Start provides separate templates for these options. It also lets you configure Classless Inter-Domain Routing (CIDR) blocks, instance types, and {partner-product-short-name} settings. Two different deployment cluster architectures are also provided in each deployment options: single cluster architecture or multicluster architecture.
>>>>>>> 05d72d3 (add multicluster)
