// Edit this placeholder text as necessary to describe the deployment options.

== Sign in to your AWS account

1. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see Planning the deployment, earlier in this guide.

2. Ensure that your AWS account is configured correctly, as discussed in the https://aws-quickstart.github.io/quickstart-databricks-unified-data-analytics-platform/#_technical_requirements[Technical requirements] section.

== Launch the Quick Start

1. Sign in to your AWS account, and launch the AWS CloudFormation template of your choice. Each deployment takes about 15 minutes to complete.

Deploy a Tanzu Application Platform deployment into a new VPC and install TAP into a new EKS cluster

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for the Tanzu Application Platform deployment is built. The template launches in the us-east-1 Region by default.

. On the Create stack page, keep the default setting for the template URL, and then choose Next.

. On the Specify stack details page, change the stack name if needed. 
.. Review the parameters for the template. 
.. Provide values for the parameters that require input. 
.. For all other parameters, review the default settings, and customize them as necessary.

. On the Configure stack options page, you can specify tags (key-value pairs) for resources in your stack and set advanced options. When you’re finished, choose Next.

. On the Review page, review and confirm the template settings. 
.. Under Capabilities, select the two check boxes to acknowledge that the template creates IAM resources and might require the ability to automatically expand macros.
.. Choose Create stack to deploy the stack.

. Monitor the status of the stack. When the status is CREATE_COMPLETE, the Tanzu Application Platform deployment is ready.

. To view the created resources, see the values displayed in the Outputs tab for the stack.

The following values should be available to use from the Outputs tab:
* Elastic IP of Bootstrap VM
* TAP GUI URL