This Partner Solution deploys {partner-product-name} ({partner-product-acronym} {partner-product-version}) to the AWS Cloud. This Partner Solution is for users who want a repeatable and customizable reference deployment for https://tanzu.vmware.com/application-platform[{partner-product-name}^] on Amazon Elastic Kubernetes Service (Amazon EKS {eks-version}) using AWS CloudFormation. This guide provides instructions for deploying the {partner-product-short-name} to Amazon EKS clusters. For more information about {partner-product-short-name}, refer to https://tanzu.vmware.com/application-platform[VMware Tanzu Application Platform^].

[WARNING]
====
Due to breaking changes from upstream https://github.com/aws-quickstart/quickstart-amazon-eks/releases/tag/v5.0.0[EKS QuickStart CloudFormation Stack^],
if you have previously installed {partner-product-acronym} through AWS QuickStart or have installed other resources using EKS QuickStart version earlier
than v5.0.0 then you need to delete the following CloudFormation Stacks: 

* the eks-quickstart-RegionalSharedResources in all Regions
* the eks-quickstart-AccountSharedResources

Deleting the above can affect existing EKS deployments, alternatively, you can create a new AWS account.
====

For more information about changes please refer to the <<release-notes, Release Notes>>.
