//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Planning the Deployment

=== Specialized Knowledge

This deployment requires a moderate level of familiarity with AWS services. If you’re new to AWS, see https://aws.amazon.com/getting-started/[Getting Started Resource Center] and https://aws.amazon.com/training/[AWS Training and Certification] These sites provide materials for learning how to design, deploy, and operate your infrastructure and applications on the AWS Cloud.

=== AWS Account

If you don’t already have an AWS account, create one at https://aws.amazon.com by following the on-screen instructions. Part of the sign-up process involves receiving a phone call and entering a PIN using the phone keypad.

Your AWS account is automatically signed up for all AWS services. You are charged only for the services you use.

=== Technical Requirements

Before you launch the Quick Start, review the following information and ensure that your account is properly configured. Otherwise, deployment might fail.

==== Resource quotas

If necessary, request https://console.aws.amazon.com/servicequotas/home?region=us-east-2#!/[service quota increases] for the following resources. You might need to request increases if your existing deployment currently uses these resources and if this Quick Start deployment could result in exceeding the default quotas. The https://console.aws.amazon.com/servicequotas/home?region=us-east-2#!/[Service Quotas console] displays your usage and quotas for some aspects of some services. For more information, see https://docs.aws.amazon.com/servicequotas/latest/userguide/intro.html[What is Service Quotas?] and https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html[AWS service quotas].

[cols="Resource","This deployment uses"]
|===
|VPCs
|1

|Subnets
|6

|Security Groups
|2

|Internet Gateways
|1

|NAT Gateways
|3

|S3 Buckets
|1

|ECR Repositories
|4

|EKS Clusters
|1

|Secrets
|3

|EC2 (m5.xlarge)
|1

|Route 53 Private Zone
|1
|===

==== IAM Permissions

Before launching the Quick Start, you must sign in to the AWS Management Console with IAM permissions for the resources that the templates deploy. The AdministratorAccess managed policy within IAM provides sufficient permissions, although your organization may choose to use a custom policy with more restrictions. For more information, see https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html[AWS managed policies for job functions].

==== Prepare your Tanzu Network Account

One of the requirements for this QuickStart to deploy automatically will be that you have already created a Tanzu Network Login and received an API token to use by the automation scripts. If you do not already have a valid Tanzu Network login, then you can start by going here: https://network.pivotal.io/[VMWare Tanzu Network]. Once on this web page, you will need to perform the following steps:

1. Click on "Sign In" link in the top right corner