//Add any unique troubleshooting steps here.

For troubleshooting common Quick Start issues, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

== TAP GUI Connectivity (optional)

In order to validate and verify connectivity to the Tanzu Application Platform, a Windows based Bastion VM has been deployed into one of the Public Subnets. This VM can be used to access the URL provided within the Outputs tab after the Cloud Formation deployment is complete. The TAP GUI is not available via a public URL, but you can certainly connect a VPC or Direct Connect to the newly created VPC to allow for direct access from your enterprise network. 

== Troubleshoot TAP Deployment

*Installation: you can view some common installation troubleshooting steps within the official VMware TAP documentation https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-troubleshooting-tap-troubleshoot-install-tap.html[here].

*Usage: you can view some common usage troubleshooting steps within the official VMware TAP documentation https://docs.vmware.com/en/Tanzu-Application-Platform/1.1/tap/GUID-troubleshooting-tap-troubleshoot-using-tap.html[here].


*Problem:*

Failure to accept an End User License Agreement error

*Explanation:*

You cannot access the Tanzu Application Platform or one of its components from VMware Tanzu Network before accepting the relevant EULA in VMware Tanzu Network.

*Solution:*

Follow the steps in Accept the End User License Agreements in Installing the Tanzu CLI https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.1/tap/GUID-install-tanzu-cli.html[here].

SSH into the EC2 instance (TAPLinuxBastionInstance)

you can see the error details in .status.usefulErrorMessage by running:

----
tanzu package installed list -A
tanzu package installed get <PACKAGE-NAME>  --namespace tap-install
----
where PACKAGE-NAME is the name of the package to target.

Run below commands

. (optional) If you have chosen to relocate TAP images to ECR

  /home/ubuntu/tap-setup-scripts/src/tap-main.sh -c relocate

. Run TAP install

  /home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install

*Problem:*

After TAP installation is complete, one or more packages fails to reconcile

*Explanation:*

Often, the cause is one of the following:

  - Your infrastructure provider takes longer to perform tasks than the timeout value allows.
  - A race condition between components exists.

*Solution:*

SSH into the EC2 instance (TAPLinuxBastionInstance)

Verify the installation status by running:
----
tanzu package installed list -A
----

If the installation has stopped running, one or more reconciliations have likely failed.
Run below command
----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install
----
