//Add any unique troubleshooting steps here.

For troubleshooting common Quick Start issues, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

=== {partner-product-name} documentation

Refer to the following resources to troubleshoot {partner-product-name}.

* https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-troubleshooting-tap-troubleshoot-install-tap.html[Troubleshoot installing Tanzu Application Platform]
* https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-troubleshooting-tap-troubleshoot-using-tap.html[Troubleshoot using Tanzu Application Platform]

=== FAQ

'''
*Q.* I can't access the {partner-product-short-name} user interface.

*A.* The following issues can cause you to not be able to access the {partner-product-short-name} user interface after deployment.

* The deployment failed to complete successfully.
+
. Verify that the CloudFormation stack deployment completed successfully.
. If the stack deployed successfully, review the {partner-product-short-name} bootstrap logs.
.. Sign in to the https://us-east-1.console.aws.amazon.com/console/home?region=us-east-1#[AWS Management Console] and open the CloudWatch console.
.. In the left navigation pane, choose *Log groups*.
.. Choose the `+/aws/quickstart/tanzu-application-platform/<stack ID>+` log group.
.. Choose the `+<instance ID>_/var/log/cloud-init-output.log+` log stream.
.. On the **Log events** page, verify that the bootstrapping completed successfully. If the bootstrapping completed successfully, then the issue might be the location you are connecting from.

[NOTE]
====
* Logs can also be found in the `+/var/log/cloud-init-output.log+` file on the Linux bastion host.
* `+<stack ID>+` used in the CloudWatch log group name is the ID of the AWS CloudFormation stack, and `+<instance ID>+` used in the CloudWatch log stream name is the ID of the Amazon EC2 Linux bastion host, respectively.
====

* You are attempting to accessing the the site from a location that doesn't have connectivity to the {partner-product-short-name} GUI. The {partner-product-short-name} website GUI URL can only be accessed from endpoints with a route to the private VPC network, such as from the Amazon EC2 Windows bastion host instance.

'''


*Q.* {partner-product-short-name} installation failed with a EULA error.

*A.* You must accept the relevant End User License Agreements (EULAs) before you can download the {partner-product-short-name} packages from the {partner-registry}. For more information, refer to https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.2/tap/GUID-install-tanzu-cli.html#accept-the-end-user-license-agreements-0[Accept the End User License Agreements].

For more details about a `+.status.usefulErrorMessage+` error, connect to the Linux bastion host using SSH. Then run the following commands. For `<PACKAGE-NAME>`, substitute the name of the package to target.

----
tanzu package installed list -A
tanzu package installed get <PACKAGE-NAME> --namespace tap-install
----

Run the following commands:

. (Optional) If you have chosen to relocate {partner-product-short-name} images to Amazon ECR and this did not complete successfully, run (takes 30-45 minutes):

  /home/ubuntu/tap-setup-scripts/src/tap-main.sh -c relocate

. Run the {partner-product-short-name} install:

  /home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install

[.big]*One or more {partner-product-short-name} packages fails to reconcile*

*Explanation*

Potential causes include:

* An infrastructure issue causing the task to take longer to run than the timeout value allows.
* A race condition between components.

*Solution*

SSH into the Linux bastion host instance, and verify the installation status by running:

----
tanzu package installed list -A
----

If the installation has stopped running, one or more reconciliations have likely failed.
If so, run the following command

----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install
----

[.big]*It's been more than 4 minutes, but the Windows bastion host administrator password still isn't available*

*Explanation*

An Amazon EC2 Key Pair of type ED25519 was likely selected for the deployment, not RSA.
As of June 23rd, 2022, Amazon EC2 Windows instances do not yet support ED25519 keys (https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-key-pairs.html[reference]).
If a Key Pair of type ED25519 is selected for this deployment, the CloudFormation stack will still deploy successfully, but you will not be able to retrieve the Windows bastion host's automatically generated password.

*Solution*

Verify that the Amazon EC2 Key Pair selected for the deployment is of type RSA, not ED25519.

Options to remediate include:

. https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ResettingAdminPassword_EC2Launchv2.html[Reset the Windows administrator password using EC2 Launch v2]
. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html[Update the CloudFormation stack] to use a Key Pair with the supported type: RSA.
  Implementing this option requires replacing all Amazon EC2 instances that use this key, which includes both the Windows and Linux bastion hosts, as well as the EKS nodes (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-keyname[reference]).
. Customize the CloudFormation template to use a separate Key Pair for the Windows bastion host and then update the CloudFormation stack.
  Implementing this option will only replace the Windows bastion host instance.
  Instructions for implementing this are beyond the scope of this guide.
. Contact https://aws.amazon.com/contact-us/[AWS Technical support]
