//Add any unique troubleshooting steps here.

For troubleshooting common Partner Solution issues, refer to the https://fwd.aws/rA69w?[AWS Partner Solution General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

=== {partner-product-name} documentation

Refer to the following resources to troubleshoot {partner-product-name}.

* https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/troubleshooting-tap-troubleshoot-install-tap.html[Troubleshoot installing {partner-product-short-name}^]
* https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/troubleshooting-tap-troubleshoot-using-tap.html[Troubleshoot using {partner-product-short-name}^]

=== I can't access the {partner-product-short-name} user interface

The following issues can cause you to not be able to access the {partner-product-short-name} user interface after deployment.

* The deployment failed to complete successfully.
+
. Verify that the CloudFormation stack deployment completed successfully.
. If the stack deployed successfully, review the {partner-product-short-name} bootstrap logs.
.. Sign in to the https://console.aws.amazon.com/console/home[AWS Management Console^], and open the CloudWatch console.
.. In the left navigation pane, choose *Log groups*.
.. Choose the `+/aws/quickstart/tanzu-application-platform/<stack ID>+` log group.
.. Choose the `+<instance ID>_/var/log/cloud-init-output.log+` log stream.
.. On the **Log events** page, verify that the bootstrapping completed successfully. If the bootstrapping completed successfully, then the issue might be the location you are connecting from.

[NOTE]
====
* Logs can also be found in the `+/var/log/cloud-init-output.log+` file on the Linux bastion host.
* `+<stack ID>+` used in the CloudWatch log group name is the ID of the AWS CloudFormation stack, and `+<instance ID>+` used in the CloudWatch log stream name is the ID of the Amazon EC2 Linux bastion host, respectively.
====

* You are attempting to accessing the site from a location that doesn't have connectivity to the {partner-product-short-name} GUI. The {partner-product-short-name} website GUI URL can only be accessed from endpoints with a route to the private VPC network, such as from the Amazon EC2 Windows bastion host instance.

=== {partner-product-short-name} installation failed with a EULA error

You must accept the relevant EULAs before you can download the {partner-product-short-name} packages from the {partner-registry}. For more information, refer to https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/install-tanzu-cli.html#accept-the-end-user-license-agreements-0[Accept the End User License Agreements^].

For more details about the `+.status.usefulErrorMessage+` error, connect to the Linux bastion host using SSH. Then run the following commands. For `<PACKAGE-NAME>`, substitute the name of the package to target.

----
tanzu package installed list -A
tanzu package installed get <PACKAGE-NAME> --namespace tap-install
----

If you have chosen to relocate {partner-product-short-name} images to Amazon ECR and this did not complete successfully, run the following command. This command takes 30–45 minutes to complete.

----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c relocate
----

Run the following command to install {partner-product-short-name}.

----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install
----

=== One or more {partner-product-short-name} packages failed to reconcile

Potential causes include:

* An infrastructure issue causing the task to take longer to run than the timeout value allows.
* A race condition between components.

Connect to the Linux bastion host using SSH. Then run the following command to verify the installation status.

----
tanzu package installed list -A
----

If the installation has stopped running, one or more reconciliations have likely failed.
If so, run the following command.

For the single cluster install of Quickstart, run the following command.
----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install single
----

For the multi cluster install of Quickstart, run the command against the cluster with packages not reconciling. The cluster types for multi cluster are "view", "run", "iterate", or "build." Pass the cluster type into the install command.
----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install <cluster-type>
----

=== It's been more than four minutes and the Windows bastion host administrator password still isn't available

It is likely that during deployment an ED25519 key pair was used instead of an RSA key pair. If you select an ED25519 key pair for this deployment, the CloudFormation stack deploys successfully, but you will be unable to retrieve the automatically generated password for the Windows bastion host.

As of June 23rd, 2022, Amazon EC2 Windows instances do not support ED25519 key pairs. For more information, refer to https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-key-pairs.html[Amazon EC2 key pairs and Windows instances^].

Verify that an RSA key pair used during deployment. If not, try the following options:

* https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ResettingAdminPassword_EC2Launchv2.html[Reset the Windows administrator password using EC2Launch v2^]

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html[Update the CloudFormation stack^] to use an RSA key pair, which will replace all Amazon EC2 instances (Windows and Linux) and Amazon EKS nodes that use this key. For more information, refer to the https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-keyname[documentation^].

* Customize the CloudFormation template to use a separate key pair for the Windows bastion host. Then update the CloudFormation stack. This option only replaces the Windows bastion host instance. Instructions for implementing this are beyond the scope of this guide.

* https://aws.amazon.com/contact-us/[Contact AWS technical support^].

=== Quickstart deployment not completing

If a deployment takes over two hours to complete, it is possible that the CloudFormation resources failed to deploy.

* The deployment failed to complete successfully.
+
. Verify that the CloudFormation stack deployment completed successfully.
. If the stack deployed successfully, review the {partner-product-short-name} bootstrap logs.
.. Sign in to the https://console.aws.amazon.com/console/home[AWS Management Console^], and open the CloudWatch console.
.. In the left navigation pane, choose *Log groups*.
.. Choose the `+/aws/quickstart/tanzu-application-platform/<stack ID>+` log group.
.. Choose the `+<instance ID>_/var/log/cloud-init-output.log+` log stream.
.. On the **Log events** page, verify that the bootstrapping completed successfully. If the bootstrapping completed successfully, then the issue might be the location you are connecting from.
. Verify that the TAP package reconciliation and install scripts succeeded.
.. In the CloudFormation console, choose the inner most failed nested stack.
.. Choose the "Events" tab and look for the error description under "Status Reason." If the error can be corrected, update the stack with the "Stack Actions" dropdown on the right corner.
.. If the stack is in "ROLLBACK_FAILED" state delete the stack and redeploy Quickstart.

[NOTE]
====
* Logs can also be found in the `+/var/log/cloud-init-output.log+` file on the Linux bastion host.
* `+<stack ID>+` used in the CloudWatch log group name is the ID of the AWS CloudFormation stack, and `+<instance ID>+` used in the CloudWatch log stream name is the ID of the Amazon EC2 Linux bastion host, respectively.
====

=== Diagnosing input parameter failures

If some input parameters are invalid they may cause the deployment to fail.

* The following are some examples of invalid parameters.
+
. Availability zones that are not present or restricted in selected AWS region.
. The list of availability zones and number of availability zones do not match.
. Remote access CIDR is invalid or not formatted correctly.
. Key pair does not exist.

* Ensure the parameters are valid.
+
. Verify that availability zones are present in the region you are deploying to.
. Verify that the list of availability zones and the number of availability zones match.
. Provide the remote access CIDR for your machine to connect to the Windows or Linux Bastion EC2 instance.
. If you do not have a key pair, create a new one and it will show up in the drop down.

=== Shared resources are not removed after previous Quickstart deletion

By design, RegionalSharedResources and AccountSharedResources do not delete when Quickstart is deleted. These resources persist between subsequent deployments.

* If the shared resources failed to deploy, delete them. If they fail to delete, manually deleting IAM roles may be necessary. There are two ways to manually delete these roles:
+
. Open the IAM console and search for "eks-quickstart" and the specific Quickstart roles will show up. Delete them then try deleting the shared resource stack that failed to deploy in the CloudFormation console.
. To see a comprehensive list of roles associated with the failed stack, open the CloudFormation console, choose the stack name and select the Resources tab. Delete any roles that succeeded to provision then try to delete the stack.
If there are multiple Quickstarts running, AccountSharedResources will span across regions. To redeploy AccountSharedResources after cleanup, delete roles and deploy the Quickstart in one region.

=== CloudFormation deployment fails using custom IAM role

The configuration to deploy with a custom IAM role is optional and not to be used to deploy Quickstart.

=== Diagnosing TAP workload failures

CloudFormation and TAP may successfully deploy but if the workload fails, the TAP workload URL will not be accessible from the Windows Bastion EC2 instance and the workload will not be visible in the TAP GUI supply chain.

Connect to the Linux bastion host using SSH. Then run the following commands to view the workload logs.

----
tanzu apps workload list -n tap-workload
tanzu apps workload tail tanzu-java-web-app-workload -n tap-workload --since 10m –timestamp
----

If the logs are free of errors, check the DNS configuration.

Go to Route53 console and ensure the private zone has the k8 cluster envoy-IP configured in the CNAME records.



== Release Notes [[release-notes]]

// git log --reverse origin/main...v1.4.0 -- ':!/ci/'

// Changelog links
:imds-v2: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
:tap-1_4_2-cl: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/release-notes.html#v142-0
:ce-1_4_1-cl: https://docs.vmware.com/en/Cluster-Essentials-for-VMware-Tanzu/1.4/cluster-essentials/release-notes.html#v141-0
:eks-1_24-cl: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.24
:eksqs-5_0_0-cl: https://github.com/aws-quickstart/quickstart-amazon-eks/releases/tag/v5.0.0

=== Version 1.4.2+aws.1
* Bugfix: Relocation of the TAP images was broken, this release fixes that.
* Removed the following configuration options:
** EKS Cluster name.
* The bastion hosts now use {imds-v2}[Instance Metadata Service Version 2 (IMDSv2)].
* We changed how we check and deploy the shared resources stacks
  (`eks-quickstart-RegionalSharedResources` & `eks-quickstart-AccountSharedResources`) which results in slightly faster deployments
  and less chance to run into race-conditions.

=== Version 1.4.2+aws.0
* The stack now reports the status of the  {partner-product-short-name} deployment and installation of the sample application  after all of the infrastructure has been deployed.
* Fixed an issue that occurred when deleting VPCs because of stale security groups.
* Upgraded the following versions:
** {tap-1_4_2-cl}[{partner-product-acronym}^] 1.4.2.
** {ce-1_4_1-cl}[ClusterEssentials^] 1.4.
** {eksqs-5_0_0-cl}[EKS QuickStart^] 5.0.0.
** {eks-1_24-cl}[EKS^] 1.24.
* Removed the following configuration options:
** {partner-product-short-name} version.
** EKS version.
** Linux Bastion host AMI.
** Linux Bastion host's SSH port.
** Sample application name.
* Fixed an issue with downloading artifacts (for example, `kubectl`) for Regions other than `us-east-1`.

=== Version 1.4.0
* You can now deploy a multicluster architecture by setting the *EKS single or multicluster / TAP cluster architecture* (`TAPClusterArch`) parameter to `multi`.
