//Add any unique troubleshooting steps here.

For troubleshooting common Partner Solution issues, refer to the https://fwd.aws/rA69w?[AWS Partner Solution General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

=== {partner-product-name} documentation

Refer to the following resources to troubleshoot {partner-product-name}.

* https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/troubleshooting-tap-troubleshoot-install-tap.html[Troubleshoot installing {partner-product-short-name}^]
* https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/troubleshooting-tap-troubleshoot-using-tap.html[Troubleshoot using {partner-product-short-name}^]

=== I can't access the {partner-product-short-name} user interface

The following issues can cause you to not be able to access the {partner-product-short-name} user interface after deployment.

* The deployment failed to complete successfully.
+
. Verify that the CloudFormation stack deployment completed successfully.
. If the stack deployed successfully, review the {partner-product-short-name} bootstrap logs.
.. Sign in to the https://console.aws.amazon.com/console/home[AWS Management Console^], and open the CloudWatch console.
.. In the left navigation pane, choose *Log groups*.
.. Choose the `+/aws/quickstart/tanzu-application-platform/<stack ID>+` log group.
.. Choose the `+<instance ID>_/var/log/cloud-init-output.log+` log stream.
.. On the **Log events** page, verify that the bootstrapping completed successfully. If the bootstrapping completed successfully, then the issue might be the location you are connecting from.

[NOTE]
====
* Logs can also be found in the `+/var/log/cloud-init-output.log+` file on the Linux bastion host.
* `+<stack ID>+` used in the CloudWatch log group name is the ID of the AWS CloudFormation stack, and `+<instance ID>+` used in the CloudWatch log stream name is the ID of the Amazon EC2 Linux bastion host, respectively.
====

* You are attempting to accessing the site from a location that doesn't have connectivity to the {partner-product-short-name} GUI. The {partner-product-short-name} website GUI URL can only be accessed from endpoints with a route to the private VPC network, such as from the Amazon EC2 Windows bastion host instance.

=== {partner-product-short-name} installation failed with a EULA error

You must accept the relevant EULAs before you can download the {partner-product-short-name} packages from the {partner-registry}. For more information, refer to https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/install-tanzu-cli.html#accept-the-end-user-license-agreements-0[Accept the End User License Agreements^].

For more details about the `+.status.usefulErrorMessage+` error, connect to the Linux bastion host using SSH. Then run the following commands. For `<PACKAGE-NAME>`, substitute the name of the package to target.

----
tanzu package installed list -A
tanzu package installed get <PACKAGE-NAME> --namespace tap-install
----

If you have chosen to relocate {partner-product-short-name} images to Amazon ECR and this did not complete successfully, run the following command. This command takes 30–45 minutes to complete.

----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c relocate
----

Run the following command to install {partner-product-short-name}.

----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install
----

=== One or more {partner-product-short-name} packages failed to reconcile

Potential causes include:

* An infrastructure issue causing the task to take longer to run than the timeout value allows.
* A race condition between components.

Connect to the Linux bastion host using SSH. Then run the following command to verify the installation status.

----
tanzu package installed list -A
----

If the installation has stopped running, one or more reconciliations have likely failed.
If so, run the following command.

----
/home/ubuntu/tap-setup-scripts/src/tap-main.sh -c install
----

=== It's been more than four minutes and the Windows bastion host administrator password still isn't available

It is likely that during deployment an ED25519 key pair was used instead of an RSA key pair. If you select an ED25519 key pair for this deployment, the CloudFormation stack deploys successfully, but you will be unable to retrieve the automatically generated password for the Windows bastion host.

As of June 23rd, 2022, Amazon EC2 Windows instances do not support ED25519 key pairs. For more information, refer to https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-key-pairs.html[Amazon EC2 key pairs and Windows instances^].

Verify that an RSA key pair used during deployment. If not, try the following options:

* https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ResettingAdminPassword_EC2Launchv2.html[Reset the Windows administrator password using EC2Launch v2^]

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html[Update the CloudFormation stack^] to use an RSA key pair, which will replace all Amazon EC2 instances (Windows and Linux) and Amazon EKS nodes that use this key. For more information, refer to the https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-keyname[documentation^].

* Customize the CloudFormation template to use a separate key pair for the Windows bastion host. Then update the CloudFormation stack. This option only replaces the Windows bastion host instance. Instructions for implementing this are beyond the scope of this guide.

* https://aws.amazon.com/contact-us/[Contact AWS technical support^].


== Release Notes [[release-notes]]

// git log --reverse origin/main...v1.4.0 -- ':!/ci/'

// Changelog links
:tap-1_4_1-cl: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.4/tap/release-notes.html#v141-0
:ce-1_4_1-cl: https://docs.vmware.com/en/Cluster-Essentials-for-VMware-Tanzu/1.4/cluster-essentials/release-notes.html#v141-0
:eks-1_24-cl: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.24
:eksqs-5_0_0-cl: https://github.com/aws-quickstart/quickstart-amazon-eks/releases/tag/v5.0.0

* Version 1.4.1
** The stack reports back if the TAP deployment and the installation of the
   sample application succeeded after all the infrastructure has been deployed
** Deletion issues, where VPCs could not be cleaned up because of left-over
   security groups, has been fixed
** Version upgrades to:
*** {tap-1_4_1-cl}[{partner-product-acronym}^] 1.4.1
*** {ce-1_4_1-cl}[ClusterEssentials^] 1.4
*** {eksqs-5_0_0-cl}[EKS QuickStart^] 5.0.0
*** {eks-1_24-cl}[EKS^] 1.24
** Removed configuration options for:
*** Version of {partner-product-short-name}
*** Version of EKS
*** Linux Bastion host AMI
*** Linux Bastion host's SSH port
*** sample application name
** Download of artifacts (e.g. `kubectl`) has been fixed for regions other than `us-east-1`
* Version 1.4.0
** Multi cluster architecture has been introduced
